In [1]:
import pandas as pd
data = pd.read_csv(r"amazon_cells_labelled.txt", sep='\t', header=None)
data.head()

C:\Users\Leapfrog\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [2]:
X = data.iloc[:,0] # extract column with review
y = data.iloc[:,-1] # extract column with sentiment

In [3]:
# tokenize the news text and convert data in matrix format
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words='english')
X_vec = vectorizer.fit_transform(X)
X_vec = X_vec.todense() # convert sparse matrix into dense matrix
X_vec

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [4]:
import numpy as np
from sklearn.feature_extraction.text import TfidfTransformer

# Assuming X_vec is your input matrix
X_vec = np.asarray(X_vec)  # Convert np.matrix to np.ndarray

tfidf = TfidfTransformer()  # By default applies "l2" normalization
X_tfidf = tfidf.fit_transform(X_vec)
X_tfidf = X_tfidf.todense()
print(X_tfidf)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
##################Apply Naive Bayes algorithm to train data####################

# Extract the news body and labels for training the classifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size = 0.25, random_state = 0)

In [6]:

from sklearn.naive_bayes import MultinomialNB

# Convert np.matrix to np.ndarray
X_train = np.asarray(X_train)
y_train = np.asarray(y_train)

clf = MultinomialNB()
clf.fit(X_train, y_train)


MultinomialNB()

In [7]:
# Convert np.matrix to np.ndarray
X_test = np.asarray(X_test)

# Predicting the Test set results
y_pred = clf.predict(X_test)

In [8]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 87,  33],
       [ 20, 110]], dtype=int64)

In [9]:
###################################Fitting SVM to the Training set#############################################
from sklearn.svm import SVC
classifier = SVC(kernel='linear')
classifier.fit(X_train, y_train)

SVC(kernel='linear')

In [10]:
y_pred = classifier.predict(X_test)

In [11]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[102,  18],
       [ 33,  97]], dtype=int64)

In [12]:
#pickling the model for reuse
import pickle
pickle.dump(vectorizer, open("vectorizer_sa", 'wb')) # Save vectorizer for reuse
pickle.dump(classifier, open("nb_sa", 'wb')) # Save classifier for reuse

### Summary
1. Load Data: Read the dataset from a tab-separated text file into a DataFrame.
2. Extract Features and Labels: Separate the review texts (X) and sentiment labels (y).
3. Vectorize Text: Convert text reviews into a feature matrix using CountVectorizer.
4. Apply TF-IDF: Transform the feature matrix to TF-IDF format using TfidfTransformer.
5. Split Data: Split the dataset into training and testing sets.
6. Train Naive Bayes: Train a Naive Bayes classifier using the training data.
7. Evaluate Naive Bayes: Predict and evaluate the test data with the Naive Bayes model using a confusion matrix.
8. Train SVM: Train a Support Vector Machine (SVM) classifier using the training data.
9. Evaluate SVM: Predict and evaluate the test data with the SVM model using a confusion matrix.
10. Save Models: Save the vectorizer and SVM model to pickle files for future use.